### PR TITLE
Update dep.s to adapt to OTP 24

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
Prevent `erlang:get_stacktrace/0` -related issues.

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
I'm removing 20.3 from the tests[*], since `cowboy` 2.8.0 does not like that.

---

[*] I'm also making sure we use a more modern 23 😄

**Comment by paulo-ferraz-oliveira** [comment]
@elbrujohalcon, if you have the time can you also look into https://github.community/t/github-actions-pull-requests-always-include-some-outdated-checks/16157 to get rid of those "Expected — Waiting for status to be reported." that are stuck there? Thanks,

**Comment by elbrujohalcon** [comment]
https://hex.pm/packages/cowboy_swagger/2.2.1

**Comment by paulo-ferraz-oliveira** [comment]
That you, sir.

**Pull request merged**
