### PR TITLE
Fix/for xref and dialyzer

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
I also noticed:
1. https://github.com/inaka/shotgun/issues/178 happening, but didn't want to fix it, since I'm not at ease with gen_statem yet;
2. some `-spec(_).`s missing in the test modules to which I didn't pay attention either;
3. compilation of aleppo is issuing some spec. -related warnings

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
xref and dialyzer analysis + tests was performed for:
- OTP 19.3
- OTP 20.3
- OTP 21.3
- OTP 22.1

**Comment by paulo-ferraz-oliveira** [comment]
Sure. I'll check what can be done pertaining your comment. @elbrujohalcon, are you OK with the other non-ignore_xref changes?

**Comment by paulo-ferraz-oliveira** [comment]
`{xref_warnings, _}` seems to output the same whether it's `true` or `false`.

**Comment by paulo-ferraz-oliveira** [comment]
https://github.com/inaka/cowboy_swagger/pull/117/commits/e4423565e665f3784a540ac3f5dd16ff959a02b1: I think I managed to respect your needs and the PR intentions.

**Comment by elbrujohalcon** [comment]
Cool, thanks @paulo-ferraz-oliveira !! Great addition :)

**Comment by paulo-ferraz-oliveira** [comment]
Many thanks!

**Pull request merged**
