### PR TITLE
support component parameters

### PR DESCRIPTION
**Pull request by zhongwencool**
support component parameters.

```json
"components": {
  "schemas": {...}
  "parameters":  
      "per-page": {
         "name": "per_page",
         "description": "Results per page (max 100)",
         "in": "query",
         "schema": {
            "type": "integer",
            "default": 30
         }
       },
      "cursor": {
        "name": "cursor",
        "description": "Used for pagination....",
        "in": "query",
        "required": false,
        "schema": {
           "type": "string"
        }
      }
}
```
use as ref:
```json
"parameters": [
          {
            "$ref": "#/components/parameters/per-page"
          },
          {
            "$ref": "#/components/parameters/cursor"
          }
        ]
```

### CODE REVIEW

**Comment by zhongwencool** [comment]
ping @elbrujohalcon :0

**Review by elbrujohalcon — APPROVED** [review]

**Comment by elbrujohalcon** [comment]
Hummm… it looks like you introduced an unused export… 🤔

**Comment by zhongwencool** [comment]
> Hummm… it looks like you introduced an unused export… 🤔

`cowboy_swagger:get_existing_definitions/1` only use by ct test, I change it to `cowboy_swagger:get_existing_definitions/2`.

I let xref to ignore this.

**Comment by elbrujohalcon** [comment]
👌🏻

**Comment by elbrujohalcon** [comment]
Well… now elvis is complaining 🤷🏻

**Comment by zhongwencool** [comment]
> Well… now elvis is complaining 🤷🏻

done....

**Comment by elbrujohalcon** [comment]
😢  We still have trailing whitespaces 🤷🏻

**Comment by zhongwencool** [comment]
@elbrujohalcon WOW, Thank you very much for this very useful library. 👍 
Could you give me a new tag?

**Comment by elbrujohalcon** [comment]
You [got it](https://hex.pm/packages/cowboy_swagger/2.5.0)!

**Pull request merged**
