### PR TITLE
Replace Travis CI with GitHub Actions

### LINKED ISSUE #122: Move from Travis CI to GitHub Actions?
Would you be interested in a pull request that moves CI from Travis CI to GitHub Actions, or at least adds GitHub Actions alongside Travis CI? It seems travis-ci.org will stop being useful from Dec 31 2020. I can do it, except that I think you need to create the workflow yml, first, in `master`, after which I can branch off of.

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
I think you need to "activate" GitHub Actions on `master` after which I can rebase this for testing.

Closes #122.

### CODE REVIEW

**Comment by elbrujohalcon** [comment]
I think this is mergeable as it is, no need for rebasing.

**Comment by elbrujohalcon** [comment]
I merged it… Feel free to send another PR if you want to test it, @paulo-ferraz-oliveira.

**Comment by paulo-ferraz-oliveira** [comment]
> I merged it… Feel free to send another PR if you want to test it, @paulo-ferraz-oliveira.

Only if there's errors 😄 as soon as you merge the Action kicks in.

**Comment by paulo-ferraz-oliveira** [comment]
I created #124 not due to `error` but due to `itch` (and that needed some scratching).

**Pull request merged**
