### PR TITLE
handle openapi 3.0 format, use new swagger-ui

### PR DESCRIPTION
**Pull request by szlartibartfaszt79**
- handle openapi 3.0 format
- copy latest swagger-ui
- remove default swagger config parameter for openapi config parameter using

### CODE REVIEW

**Comment by szlartibartfaszt79** [comment]
> I like this, but… don't we need to update/create some tests for this change?

You're right. I fixed the failed test, but I have to extend the test cases with openapi 3.0 format.

**Comment by szlartibartfaszt79** [comment]
WIP

**Comment by szlartibartfaszt79** [comment]
Need I squash before merge? 
There were two minor fixes after approval. This version is used internally for half year without any issues.

**Comment by elbrujohalcon** [comment]
Merged. Thanks @szlartibartfaszt79 :)

**Comment by szlartibartfaszt79** [comment]
Thanks for the merge :-)
Unfortunately README.md is not up-to-date according to openapi specification. Moreover it contains some wrong data, for example: _swagger => "2.0"_. It will be fixed as soon as possible in a new PR. I apologize for the inconvenience!

**Pull request merged**
