### PR TITLE
virtual key "$required" was added to build_definition/2

### PR DESCRIPTION
**Pull request by rk108**
For using 'required' key swagger_specifitaion in '$ref' schema defiintion.

### CODE REVIEW

**Review by elbrujohalcon — CHANGES_REQUESTED** [review]
Hi, @rk108 … Thanks for your contribution!

Do you mind improving formatting a bit by putting all commas and curly braces in the same column and adding a test for this?

**Comment by paulo-ferraz-oliveira** [comment]
It's possible this is either no longer relevant or won't be worked on soon. Shall we close it, with a "this is stale" not (such as this one) and thus inform the creator of the pull request?

**Comment by elbrujohalcon** [comment]
Yes. Go for it, @paulo-ferraz-oliveira

**Comment by paulo-ferraz-oliveira** [comment]
Closing as "stale".

**Pull request closed without merging**
